export const MOCK_THERAPISTS = [
  {
    id: '1',
    name: 'Dr. Fatima Rahman',
    specialization: ['Depression', 'Anxiety', 'CBT'],
    experience: 8,
    rating: 4.9,
    bio: 'Specialized in cognitive-behavioral therapy and anxiety management.',
    image: 'https://i.ibb.co.com/QFhSjG0g/confident-doctor-clinic-23-2151983463.jpg',
    sessionPrice: 1200,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    credentials: 'M.Phil Clinical Psychology, Licensed Psychologist - Bangladesh',
  },
  {
    id: '2',
    name: 'Dr. Kamal Hassan',
    specialization: ['Stress Management', 'Sleep Issues', 'Mindfulness'],
    experience: 12,
    rating: 4.8,
    bio: 'Expert in mindfulness-based stress reduction and sleep improvement.',
    image: 'https://i.ibb.co.com/sJsFzzXP/doctor-with-his-arms-crossed-white-background.jpg',
    sessionPrice: 1500,
    availability: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    credentials: 'M.D. Psychiatry, Board Certified - BCPS',
  },
  {
    id: '3',
    name: 'Dr. Nadia Akter',
    specialization: ['Trauma', 'PTSD', 'Women\'s Mental Health'],
    experience: 10,
    rating: 4.9,
    bio: 'Trauma-informed therapist specializing in women\'s mental health issues.',
    image: 'https://i.ibb.co.com/yt4b4Dt/attractive-medical-professional-uniform-standing-with-arms-crossed-against-isolated-background.jpg',
    sessionPrice: 1400,
    availability: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
    credentials: 'MA Clinical Psychology, Trauma Specialist - Bangladesh',
  },
  {
    id: '4',
    name: 'Dr. Arman Islam',
    specialization: ['Addiction', 'Substance Abuse', 'Recovery'],
    experience: 15,
    rating: 4.9,
    bio: 'Specialized addiction counselor with evidence-based treatment approaches.',
    image: 'https://i.ibb.co.com/Vc3Cdybg/handsome-young-male-doctor-with-stethoscope-standing-against-blue-background.jpg',
    sessionPrice: 1600,
    availability: ['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday'],
    credentials: 'CADC, Addiction Recovery Specialist - ICTA',
  },
];

export const MOCK_WELLNESS_RESOURCES = [
  {
    id: '1',
    title: '5-Minute Breathing Exercise',
    description: 'Simple technique to reduce anxiety and calm your nervous system.',
    content: 'Breathe in for 4 counts, hold for 4, exhale for 6...',
    category: 'exercise',
    duration: 5,
    difficulty: 'beginner',
    image: 'https://i.ibb.co.com/Fbq7f6mK/relaxed-man-breathing-fresh-air.jpg',
    tags: ['breathing', 'anxiety', 'quick'],
  },
  {
    id: '2',
    title: 'Guided Meditation for Sleep',
    description: 'Relaxing meditation to improve sleep quality.',
    content: 'Settle into a comfortable position...',
    category: 'meditation',
    duration: 20,
    difficulty: 'beginner',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    tags: ['sleep', 'meditation', 'relaxation'],
  },
  {
    id: '3',
    title: 'Understanding Anxiety: A Beginner\'s Guide',
    description: 'Comprehensive article about anxiety and coping mechanisms.',
    content: 'Anxiety is a natural response...',
    category: 'article',
    difficulty: 'beginner',
    image: 'https://i.ibb.co.com/SX17zMRP/work-burnout-anxiety-and-mental-health-with-woman-sad-worker-problem-or-fail-at-company-with.jpg',
    tags: ['anxiety', 'education', 'tips'],
  },
  {
    id: '4',
    title: 'CBT for Negative Thought Patterns',
    description: 'Interactive CBT exercise to identify and challenge negative thoughts.',
    content: 'Cognitive Behavioral Therapy focuses on...',
    category: 'cbt',
    difficulty: 'intermediate',
    image: 'https://i.ibb.co.com/Mxm6T5gp/shot-of-a-unrecognizable-woman-sitting-on-a-sofa-and-feeling-anxious.jpg',
    tags: ['cbt', 'thoughts', 'behavior'],
  },
];

export const CRISIS_RESOURCES = {
  nationalHotline: '999',
  crisisTextLine: 'Emergency Services',
  emergencyServices: '999',
  resources: [
    {
      name: 'Emergency Services',
      phone: '999',
      hours: '24/7',
    },
    {
      name: 'Bangladesh Psychological Helpline',
      phone: '01877-020020',
      hours: '24/7',
    },
    {
      name: 'SADC Crisis Line',
      phone: '1-800-662-4357',
      hours: '24/7',
    },
  ],
};

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Anonymous User',
    text: 'This platform helped me manage my anxiety in ways I never thought possible. The guided exercises are incredibly helpful.',
    rating: 5,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=User1',
  },
  {
    id: '2',
    name: 'Anonymous User',
    text: 'The therapist directory made it so easy to find the right professional. Highly recommended!',
    rating: 5,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=User2',
  },
  {
    id: '3',
    name: 'Anonymous User',
    text: 'The mood tracking feature helps me understand my patterns better. Combined with therapy, it\'s been transformative.',
    rating: 5,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=User3',
  },
];
